# Generated by Django 6.0.5 on 2026-05-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0026_game_unit_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional display name shown on leaderboard and intro modal.",
                max_length=100,
            ),
        ),
    ]
