# Generated by Django 6.0.5 on 2026-05-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0028_alter_game_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="allowed_time",
            field=models.PositiveIntegerField(
                default=1440, help_text="Per-carrier time limit in hours. Distance mode only."
            ),
        ),
    ]
