# Generated by Django 6.0.5 on 2026-05-06 22:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0029_alter_game_allowed_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When the game starts. End time is start_time + allowed_time hours.",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="allowed_time",
            field=models.PositiveIntegerField(default=1440, help_text="Total game duration in hours."),
        ),
    ]
