# Generated by Django 6.0.5 on 2026-05-06 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0030_game_start_time_alter_game_allowed_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="color",
            field=models.CharField(
                default="#7b8fa1",
                help_text="Hex colour used for the team pill on the leaderboard, e.g. #c94c35.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "Enter a 6-digit hex colour like #c94c35."
                    )
                ],
            ),
        ),
    ]
