# Generated by Django 6.0.5 on 2026-05-22 16:44

import django_resized.forms
from django.db import migrations

import backend.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0030_rename_subscribers_to_followers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkinimage",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=False,
                quality=85,
                scale=None,
                size=[2560, 2560],
                upload_to=backend.models.validators.path_and_rename,
                validators=[backend.models.validators.validate_image_size],
            ),
        ),
    ]
