# Generated by Django 6.0.5 on 2026-05-24 22:04

from django.conf import settings
from django.db import migrations, models

import backend.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0033_schedule_pending_upload_cleanup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="message",
            field=models.TextField(
                blank=True, max_length=5000, validators=[backend.models.validators.validate_no_urls]
            ),
        ),
        migrations.AddConstraint(
            model_name="checkin",
            constraint=models.CheckConstraint(
                condition=models.Q(("message__length__lte", 5000)), name="checkin_message_max_length"
            ),
        ),
    ]
