# Generated by Django 6.0.5 on 2026-05-29 11:58

from django.db import migrations

import backend.models.fields
import backend.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0034_alter_checkin_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkinimage",
            name="image",
            field=backend.models.fields.StrippedResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=False,
                quality=85,
                scale=None,
                size=[2560, 2560],
                upload_to=backend.models.validators.path_and_rename,
                validators=[backend.models.validators.validate_image_size],
            ),
        ),
    ]
