/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/account/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["account_retrieve"];
        put?: never;
        post?: never;
        delete: operations["account_destroy"];
        options?: never;
        head?: never;
        patch: operations["account_partial_update"];
        trace?: never;
    };
    "/api/account/follows/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["account_follows_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/social-accounts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description DELETE /api/account/social-accounts/ — remove a connected social account.
         *
         *     Allauth's built-in disconnect rejects users with no usable password. Since
         *     this app is passwordless (magic code always works), we bypass that check and
         *     delete the SocialAccount directly. The user must have at least one verified
         *     email address so they can still receive sign-in codes after disconnect.
         */
        delete: operations["account_social_accounts_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/code/request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Unified sign-in / sign-up endpoint. Creates the account if it doesn't exist,
         *     then triggers allauth's login-by-code flow. Always returns the same response
         *     regardless of whether the email was registered, preventing email enumeration.
         *     Rate-limited via allauth's built-in ratelimit (ACCOUNT_RATE_LIMITS[request_login_code]).
         */
        post: operations["auth_code_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["config_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["feedback_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{id}/journeys/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Map data for a Game's journeys, split from the leaderboard endpoint so
         *     table-only callers (rank lookups on the unit page, the leaderboard table
         *     itself) don't pay for the coordinate dump on every fetch. Anonymous: no
         *     identifiers in the payload.
         */
        get: operations["games_journeys_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{id}/leaderboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["games_leaderboard_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/globe-pins/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["globe_pins_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/units/{identifier}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["units_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/units/{identifier}/checkins/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["units_checkins_list"];
        put?: never;
        post: operations["units_checkins_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/units/{identifier}/checkins/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["units_checkins_destroy"];
        options?: never;
        head?: never;
        patch: operations["units_checkins_partial_update"];
        trace?: never;
    };
    "/api/units/{identifier}/follow/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["units_follow_create"];
        delete: operations["units_follow_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/units/{identifier}/guest-follow/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["units_guest_follow_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/units/{identifier}/pending-images/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["units_pending_images_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CheckIn: {
            readonly id: number;
            /** Format: date-time */
            readonly date_created: string;
            readonly created_by_username: string | null;
            readonly created_by_name: string | null;
            readonly images: components["schemas"]["CheckInImage"][];
            message?: string;
            place?: string;
            location: {
                /** @enum {string} */
                type?: "Point";
                /**
                 * @example [
                 *       12.9721,
                 *       77.5933
                 *     ]
                 */
                coordinates?: number[];
            };
            gps_location?: unknown;
            gps_accuracy_m?: number | null;
            pending_image_tokens?: string[];
            readonly within_edit_grace_period: boolean;
            anonymous_name?: string;
        };
        CheckInImage: {
            readonly id: number;
            /** Format: uri */
            image: string;
            order?: number;
        };
        CodeRequest: {
            /** Format: email */
            email: string;
        };
        CodeRequestError: {
            detail: string;
        };
        CodeRequestForbidden: {
            detail: string;
        };
        CodeRequestSuccess: {
            detail: string;
        };
        CodeRequestThrottled: {
            detail: string;
        };
        Config: {
            maptilerKey: string;
            allowRegistration: boolean;
            turnstileSiteKey: string;
        };
        FeedbackError: {
            detail: string;
        };
        FeedbackRequest: {
            message: string;
            /** Format: email */
            email?: string;
            turnstile_token?: string;
        };
        FeedbackSuccess: {
            detail: string;
        };
        Game: {
            readonly id: number;
            /** @description Display name shown on the leaderboard and intro modal. */
            name: string;
            mode?: components["schemas"]["ModeEnum"];
            /** @description Total game duration in hours. */
            allowed_time?: number;
            /** @description Floor of the drift envelope in meters. The server enforces `distance(pin, gps) ≤ max(this, reported accuracy)`, so this is the minimum allowance — never the cap. (Distance+Race modes.) */
            gps_drift_floor?: number;
            /** @description Time in hours before a check-in expires. (Hot Potato mode) */
            shelf_life?: number;
            /**
             * Format: date-time
             * @description When the game starts. End time is start_time + allowed_time hours.
             */
            start_time?: string;
            /** Format: date-time */
            readonly end_time: string;
        };
        GameJourneys: {
            game_id: number;
            journeys: components["schemas"]["JourneyEntry"][];
        };
        GlobePin: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
        };
        GlobePins: {
            pins: components["schemas"]["GlobePin"][];
        };
        GuestFollowError: {
            detail: string;
        };
        GuestFollowRequest: {
            /** Format: email */
            email: string;
            checkin_id: number;
        };
        GuestFollowSuccess: {
            detail: string;
        };
        JourneyEntry: {
            rank: number;
            team: components["schemas"]["Team"] | null;
            journey: components["schemas"]["JourneyPoint"][];
        };
        JourneyPoint: {
            /** Format: double */
            lng: number;
            /** Format: double */
            lat: number;
            date: string;
            after_end: boolean;
        };
        Leaderboard: {
            game: components["schemas"]["LeaderboardGame"];
            individual: components["schemas"]["LeaderboardIndividualEntry"][];
            teams: components["schemas"]["LeaderboardTeamEntry"][] | null;
        };
        LeaderboardGame: {
            readonly id: number;
            /** @description Display name shown on the leaderboard and intro modal. */
            name: string;
            mode?: components["schemas"]["ModeEnum"];
            /** @description Total game duration in hours. */
            allowed_time?: number;
            /** @description Floor of the drift envelope in meters. The server enforces `distance(pin, gps) ≤ max(this, reported accuracy)`, so this is the minimum allowance — never the cap. (Distance+Race modes.) */
            gps_drift_floor?: number;
            /** @description Time in hours before a check-in expires. (Hot Potato mode) */
            shelf_life?: number;
            /**
             * Format: date-time
             * @description When the game starts. End time is start_time + allowed_time hours.
             */
            start_time?: string;
            /** Format: date-time */
            readonly end_time: string;
            sort_by: components["schemas"]["SortByEnum"];
        };
        LeaderboardIndividualEntry: {
            rank: number;
            identifier: string | null;
            place: string;
            last_checkin_name: string;
            /** Format: double */
            distance_km: number;
            checkin_count: number;
            team: components["schemas"]["Team"] | null;
        };
        LeaderboardTeamEntry: {
            rank: number;
            team: components["schemas"]["Team"];
            /** Format: double */
            distance_km: number;
            checkin_count: number;
            lighter_count: number;
        };
        /**
         * @description * `relay` - Relay
         *     * `race` - Race
         *     * `hot_potato` - Hot Potato
         *     * `distance` - Distance
         * @enum {string}
         */
        ModeEnum: "relay" | "race" | "hot_potato" | "distance";
        PatchedCheckIn: {
            readonly id?: number;
            /** Format: date-time */
            readonly date_created?: string;
            readonly created_by_username?: string | null;
            readonly created_by_name?: string | null;
            readonly images?: components["schemas"]["CheckInImage"][];
            message?: string;
            place?: string;
            location?: {
                /** @enum {string} */
                type?: "Point";
                /**
                 * @example [
                 *       12.9721,
                 *       77.5933
                 *     ]
                 */
                coordinates?: number[];
            };
            gps_location?: unknown;
            gps_accuracy_m?: number | null;
            pending_image_tokens?: string[];
            readonly within_edit_grace_period?: boolean;
            anonymous_name?: string;
        };
        PatchedUser: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            readonly username?: string;
            /** Name of User */
            name?: string;
            language?: string;
            readonly admin_url?: string | null;
        };
        PendingImageUploadRequest: {
            /** Format: uri */
            image: string;
            turnstile_token?: string;
        };
        PendingImageUploadResponse: {
            token: string;
            /** Format: uri */
            preview_url: string;
        };
        SocialAccountError: {
            detail: string;
        };
        SocialAccountNotFound: {
            detail: string;
        };
        /**
         * @description * `distance_km` - distance_km
         *     * `checkin_count` - checkin_count
         * @enum {string}
         */
        SortByEnum: "distance_km" | "checkin_count";
        Stats: {
            active_unit_count: number;
            checkin_count: number;
            followers: number;
            /** Format: double */
            total_distance_traveled_km: number;
        };
        Team: {
            name: string;
            /** @description Hex colour used for the team pill on the leaderboard, e.g. #c94c35. */
            color?: string;
        };
        Unit: {
            /** @description Unique identifier for the unit, e.g. 'alpha-01'. Must start with at least three characters and end with two digits, separated by a dash. */
            identifier: string;
            /** Format: date-time */
            readonly date_created: string;
            /** @description Whether only admins can check in to this unit, primarily used for demos or for disabling lighters. */
            admin_only_checkin?: boolean;
            readonly team: components["schemas"]["Team"] | null;
            readonly checkin_count: number;
            readonly follower_count: number;
            /** Format: double */
            readonly distance_traveled_km: number;
            readonly is_following: boolean;
            readonly can_check_in: boolean;
            readonly is_gps_enforced: boolean;
            readonly game: components["schemas"]["Game"] | null;
        };
        User: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            readonly username: string;
            /** Name of User */
            name?: string;
            language?: string;
            readonly admin_url: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    account_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    account_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    account_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    account_follows_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unit"][];
                };
            };
        };
    };
    account_social_accounts_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialAccountError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialAccountNotFound"];
                };
            };
        };
    };
    auth_code_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CodeRequest"];
                "multipart/form-data": components["schemas"]["CodeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeRequestSuccess"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeRequestError"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeRequestForbidden"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeRequestThrottled"];
                };
            };
        };
    };
    config_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
        };
    };
    feedback_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["FeedbackRequest"];
                "multipart/form-data": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSuccess"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackError"];
                };
            };
        };
    };
    games_journeys_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameJourneys"];
                };
            };
        };
    };
    games_leaderboard_retrieve: {
        parameters: {
            query?: {
                /** @description Unit identifier whose row should keep its identifier in the response. All other rows return identifier=null so the public endpoint cannot be used to enumerate unit slugs. */
                from?: string;
            };
            header?: never;
            path: {
                id: number;
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Leaderboard"];
                };
            };
        };
    };
    globe_pins_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobePins"];
                };
            };
        };
    };
    stats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
        };
    };
    units_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unit"];
                };
            };
        };
    };
    units_checkins_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckIn"][];
                };
            };
        };
    };
    units_checkins_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckIn"];
                "application/x-www-form-urlencoded": components["schemas"]["CheckIn"];
                "multipart/form-data": components["schemas"]["CheckIn"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckIn"];
                };
            };
        };
    };
    units_checkins_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    units_checkins_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCheckIn"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCheckIn"];
                "multipart/form-data": components["schemas"]["PatchedCheckIn"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckIn"];
                };
            };
        };
    };
    units_follow_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    units_follow_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    units_guest_follow_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuestFollowRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["GuestFollowRequest"];
                "multipart/form-data": components["schemas"]["GuestFollowRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestFollowSuccess"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestFollowError"];
                };
            };
        };
    };
    units_pending_images_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PendingImageUploadRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PendingImageUploadRequest"];
                "multipart/form-data": components["schemas"]["PendingImageUploadRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingImageUploadResponse"];
                };
            };
        };
    };
}
